---
# yamllint disable rule:line-length rule:truthy
name: Build and Publish Addon

env:
  BUILD_ARGS: "--test"
  MONITORED_FILES: "apparmor.txt build.yaml config.yaml Dockerfile data rootfs"

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

permissions:
  contents: read
  packages: write

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      changed_files: ${{ steps.changed_files.outputs.all }}
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6.0.2

      - name: Get changed files
        id: changed_files
        uses: masesgroup/retrieve-changed-files@v3.0.0

      - name: Get addons
        id: addons
        run: |
          declare -a addons
          for addon in $(find ./ -name config.yaml | cut -d "/" -f2 | sort -u); do
            addons+=("$addon");
          done
          echo "addons=${addons[@]}" >> "$GITHUB_OUTPUT"

      - name: Get changed addons
        id: changed_addons
        run: |
          declare -a changed_addons
          for addon in ${{ steps.addons.outputs.addons }}; do
            if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon ]]; then
              for file in ${{ env.MONITORED_FILES }}; do
                  if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon/$file ]]; then
                    if [[ ! "${changed_addons[@]}" =~ $addon ]]; then
                      changed_addons+=("\"${addon}\",");
                    fi
                  fi
              done
            fi
          done

          changed=$(echo ${changed_addons[@]} | rev | cut -c 2- | rev)
          if [[ -n ${changed} ]]; then
            echo "Changed addons: $changed";
            echo "changed=true" >> "$GITHUB_OUTPUT";
            echo "addons=[$changed]" >> "$GITHUB_OUTPUT";
          else
            echo "No addon had any monitored files changed (${{ env.MONITORED_FILES }})";
          fi

  build:
    needs: init
    runs-on: ${{ matrix.runs-on }}
    if: needs.init.outputs.changed == 'true'
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} addon
    strategy:
      matrix:
        addon: ${{ fromJson(needs.init.outputs.changed_addons) }}
        arch: ["aarch64", "amd64"]
        include:
          - runs-on: ubuntu-24.04
          - runs-on: ubuntu-24.04-arm
            arch: aarch64

    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ matrix.addon }}"

      - name: Check addon
        id: check
        run: |
          if [[ "${{ steps.info.outputs.architectures }}" =~ ${{ matrix.arch }} ]]; then
             echo "build_arch=true" >> "$GITHUB_OUTPUT";
           else
             echo "${{ matrix.arch }} is not a valid arch for ${{ matrix.addon }}, skipping build";
          fi

      - name: Set build arguments
        if: steps.check.outputs.build_arch == 'true'
        run: |
          if [[ -z "${{ github.head_ref }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
              echo "BUILD_ARGS=--docker-hub-check" >> $GITHUB_ENV;
          fi

      - name: Login to GitHub Container Registry
        if: env.BUILD_ARGS == '--docker-hub-check'
        uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.addon }} addon
        if: steps.check.outputs.build_arch == 'true'
        uses: home-assistant/builder@2025.11.0
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --${{ matrix.arch }} \
            --target /data/${{ matrix.addon }} \
            --docker-hub ghcr.io/${{ github.repository_owner }} \
            --addon
